# Use root/example as user/password credentials
# to start run:> docker-compose -f docker_MySQL_Adminer.yml up -d

version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rr
    ports:
      - 3306:3306
  
  # dbMongo:
  #   image: mongo:3.6.2
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: rr
