delete from CAP where ID >= 0 and ID < 28;
insert into CAP(ID, CPC) values
(0, 'CHG PWD'),
(1, 'CR NEW TTL'),
(2, 'DIMS'),
(3, 'ED OBJ'),
(4, 'IMGS'),
(5, 'LBL PWD 1'),
(6, 'LBL PWD 2'),
(7, 'LOGIN'),
(8, 'LOGOUT'),
(9, 'NEW OBJ'),
(10, 'OBJ KIND'),
(11, 'OBJ KINDS'),
(12, 'OBJ'),
(13, 'OBJS'),
(14, 'PLH PWD 1'),
(15, 'PLH PWD 2'),
(16, 'PUB WEB'),
(17, 'RE-ORD OBJ IMGS'),
(18, 'READY'),
(19, 'STD TTLS'),
(20, 'SUBMIT'),
(21, 'TTL'),
(22, 'TTLS'),
(23, 'UNUSED IMGS DRAG'),
(24, 'UPLOD OBJ IMGS'),
(25, 'USE SDT TTL'),
(26, 'USR OBJS'),
(27, 'YEAR')
;
insert into CAP_ELEM values
(0, 'en', 'change password'),
(1, 'en', 'create new title'),
(2, 'en', 'dimensions'),
(3, 'en', 'edit object'),
(4, 'en', 'images'),
(5, 'en', 'new password'),
(6, 'en', 'new password repeated'),
(7, 'en', 'login'),
(8, 'en', 'logout'),
(9, 'en', 'new object'),
(10, 'en', 'object kind'),
(11, 'en', 'object kinds'),
(12, 'en', 'object'),
(13, 'en', 'objects'),
(14, 'en', 'enter new password'),
(15, 'en', 'repeat new password'),
(16, 'en', 'publish on website'),
(17, 'en', 're-order object images'),
(18, 'en', 'ready'),
(19, 'en', 'standard titles'),
(20, 'en', 'submit'),
(21, 'en', 'title'),
(22, 'en', 'titles'),
(23, 'en', 'unused images (drag up to assign)'),
(24, 'en', 'upload image files (klick or drag here)'),
(25, 'en', 'use standard title'),
(26, 'en', 'my recent objects'),
(27, 'en', 'year')
;