delete from CAP where ID >= 0 and ID < 44;
insert into CAP(ID, CPC) values
(0, 'AUT SITE'),
(1, 'CHG PWD'),
(2, 'CLOSE ESC'),
(3, 'CR NEW TTL'),
(4, 'DIMS'),
(5, 'ED OBJ'),
(6, 'ED STD TTL'),
(7, 'ED WHAT'),
(8, 'GOOGLE TRANS'),
(9, 'IMG'),
(10, 'IMGS'),
(11, 'LBL PWD 1'),
(12, 'LBL PWD 2'),
(13, 'LOGIN'),
(14, 'LOGOUT'),
(15, 'NEW ITEM'),
(16, 'NEW OBJ'),
(17, 'NEW STD TTL'),
(18, 'NEW TTL'),
(19, 'NEW WHAT'),
(20, 'OBJ'),
(21, 'OBJS'),
(22, 'PLH PWD 1'),
(23, 'PLH PWD 2'),
(24, 'PUB WEB'),
(25, 'RE-ORD OBJ IMGS'),
(26, 'READY'),
(27, 'SAVE CHGS'),
(28, 'SEL STD TTL'),
(29, 'STD TTLS'),
(30, 'SUBMIT'),
(31, 'TTL'),
(32, 'TTLS'),
(33, 'UNUSED IMGS DRAG'),
(34, 'UPLD IMGS'),
(35, 'USE SDT TTL'),
(36, 'USR OBJS'),
(37, 'WHAT'),
(38, 'WHATS'),
(39, 'YEAR'),
(40, 'CAP'),
(41, 'CAPS'),
(42, 'ED CAP'),
(43, 'NEW CAP')
;
insert into CAP_ELEM values
(0, 'en', 'authors site'),
(1, 'en', 'change password'),
(2, 'en', 'close / ESC'),
(3, 'en', 'create new title'),
(4, 'en', 'dimensions'),
(5, 'en', 'edit object'),
(6, 'en', 'edit standard title'),
(7, 'en', 'edit object kind'),
(8, 'en', 'google translate'),
(9, 'en', 'image'),
(10, 'en', 'images'),
(11, 'en', 'new password'),
(12, 'en', 'new password repeated'),
(13, 'en', 'login'),
(14, 'en', 'logout'),
(15, 'en', 'new item'),
(16, 'en', 'new object'),
(17, 'en', 'new standard title'),
(18, 'en', 'new title'),
(19, 'en', 'new object kind'),
(20, 'en', 'object'),
(21, 'en', 'objects'),
(22, 'en', 'enter new password'),
(23, 'en', 'repeat new password'),
(24, 'en', 'publish on website'),
(25, 'en', 're-order object images'),
(26, 'en', 'ready'),
(27, 'en', 'save changes'),
(28, 'en', 'select standard title'),
(29, 'en', 'standard titles'),
(30, 'en', 'submit'),
(31, 'en', 'title'),
(32, 'en', 'titles'),
(33, 'en', 'unused images (drag up to assign)'),
(34, 'en', 'upload image files (klick or drag here)'),
(35, 'en', 'use standard title'),
(36, 'en', 'my recent objects'),
(37, 'en', 'object kind'),
(38, 'en', 'object kinds'),
(39, 'en', 'year'),
(40, 'en', 'caption'),
(41, 'en', 'captions'),
(42, 'en', 'edit caption'),
(43, 'en', 'new caption')
;