

DROP TABLE IF EXISTS TEST;
CREATE TABLE TEST (
    ID INT NOT NULL DEFAULT 0,
    ILC CHAR(2) NOT NULL DEFAULT 'en', 
    LABEL VARCHAR(128) NOT NULL DEFAULT '',
    PRIMARY KEY (ID, ILC),
    FOREIGN KEY (ILC) REFERENCES LANG(ILC) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO TEST VALUES
    (123, 'en', '12345678901234567890')
;

SELECT * FROM TEST WHERE ID = 123;

DROP TABLE IF EXISTS TEST;
