-- all objects with 1st image
DROP VIEW IF EXISTS OBJECTS_IMG1;
CREATE VIEW OBJECTS_IMG1 AS
SELECT OBJECT as id, imgFileMini(IMG) as src from OBJECT_IMG as T1
inner join
(select OBJECT as OB2, min(ORD) as ORD2 from OBJECT_IMG GROUP BY OBJECT) as T2
ON T1.OBJECT = T2.OB2 AND T1.ORD = T2.ORD2;

SELECT * FROM OBJECTS_IMG1;

SELECT * FROM OBJECT_IMG;
